# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wiiui96mv4ab3MeCiU1rklJRwBtvhpxW
"""

import os
import json
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

class FashionCNN(nn.Module):
    def __init__(self):
        super(FashionCNN, self).__init__()
        self.conv = nn.Conv2d(1, 8, kernel_size=3, stride=1, padding=0)
        self.fc = nn.Linear(8 * 13 * 13, 10)

    def forward(self, x):
        x = torch.relu(self.conv(x))
        x = torch.max_pool2d(x, kernel_size=2, stride=2)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

def main():
    models_dir = "/content"
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    transform = transforms.Compose([transforms.ToTensor()])

    print("Loading Data...")
    trainset = torchvision.datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
    testset = torchvision.datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)
    testloader = torch.utils.data.DataLoader(testset, batch_size=1000, shuffle=False)

    model = FashionCNN().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    print("\nTraining ONE master model for 5 epochs...")
    model.train()
    for epoch in range(5):
        for images, labels in trainloader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = criterion(model(images), labels)
            loss.backward()
            optimizer.step()
        print(f"Epoch {epoch+1}/5 Complete.")

    print("\nEvaluating Accuracy...")
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for images, labels in testloader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    print(f"Accuracy: {100 * correct / total:.2f}%")

    print("\nExporting High-Precision Weights (fp32_model.json)...")
    state_dict = model.state_dict()
    model_json = {
        "conv_weight": state_dict["conv.weight"].cpu().flatten().tolist(),
        "conv_bias": state_dict["conv.bias"].cpu().flatten().tolist(),
        "fc_weight": state_dict["fc.weight"].cpu().flatten().tolist(),
        "fc_bias": state_dict["fc.bias"].cpu().flatten().tolist()
    }
    with open(os.path.join(models_dir, "fp32_model.json"), "w") as f:
        json.dump(model_json, f)

    print("Exporting High-Precision Test Image (test_image.json)...")
    image, label = testset[0]
    with torch.no_grad():
        logits = model(image.unsqueeze(0).to(device)).cpu().flatten().tolist()

    test_image_json = {
        "label": int(label),
        "data": image.flatten().tolist(),
        "expected_logits": logits
    }
    with open(os.path.join(models_dir, "test_image.json"), "w") as f:
        json.dump(test_image_json, f)

    print("Exporting High-Precision Validation Set (validation_set.json)...")
    validation_data = []
    with torch.no_grad():
        for i in range(10):
            img, lbl = testset[i]
            val_logits = model(img.unsqueeze(0).to(device)).cpu().flatten().tolist()
            validation_data.append({
                "id": i,
                "label": int(lbl),
                "data": img.flatten().tolist(),
                "expected_logits": val_logits
            })

    with open(os.path.join(models_dir, "validation_set.json"), "w") as f:
        json.dump(validation_data, f)

    print("\nSUCCESS: All files generated from the EXACT same model.")

if __name__ == "__main__":
    main()